name: niches
favicon: null
layout_spectrum: 0.2574468
typography_spectrum: 0.9148936
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: niches  and niche marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7eafa'
    - '#090915'
    - '#a1a6e0'
    - '#4b4a79'
    - '#9c3a5f'
  brandStrength: 0.5680851
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.6170213
purpose: []
