name: niches
favicon: null
layout_spectrum: 0.2419908947777003
typography_spectrum: 0.23407393274828792
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.34550799522548914
  lightness: 0.5152383311651647
  saturation: 0.6607928168959916
  rhythmicContrast: 0.03869464015588164
purpose: []
